/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ProductsIndexImport } from './routes/products/index'
import { Route as CarsIndexImport } from './routes/cars/index'
import { Route as ProductsProductIDImport } from './routes/products/$productID'
import { Route as CarsCarIDImport } from './routes/cars/$carID'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsIndexRoute = ProductsIndexImport.update({
  path: '/products/',
  getParentRoute: () => rootRoute,
} as any)

const CarsIndexRoute = CarsIndexImport.update({
  path: '/cars/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsProductIDRoute = ProductsProductIDImport.update({
  path: '/products/$productID',
  getParentRoute: () => rootRoute,
} as any)

const CarsCarIDRoute = CarsCarIDImport.update({
  path: '/cars/$carID',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/cars/$carID': {
      preLoaderRoute: typeof CarsCarIDImport
      parentRoute: typeof rootRoute
    }
    '/products/$productID': {
      preLoaderRoute: typeof ProductsProductIDImport
      parentRoute: typeof rootRoute
    }
    '/cars/': {
      preLoaderRoute: typeof CarsIndexImport
      parentRoute: typeof rootRoute
    }
    '/products/': {
      preLoaderRoute: typeof ProductsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  CarsCarIDRoute,
  ProductsProductIDRoute,
  CarsIndexRoute,
  ProductsIndexRoute,
])

/* prettier-ignore-end */
